name: ML Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de treinamento
        run: python train.py

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: classification-report
          path: report.txt
